# BA Endterm - Decision Tree

$\underline{Problem Statement}$: Given the Independent variables, we have to predict whether the Indian Cricket Team will win or lose the match.

In [1]:
# Importing the necessary Modules
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split # to split data into training and testing sets
from sklearn.model_selection import cross_val_score # for cross validation
from sklearn.metrics import confusion_matrix # to create a confusion matrix

In [2]:
import os
os.getcwd()

'C:\\Users\\SHINJINI DASGUPTA\\Downloads\\FT273034_BA_ EndTerm'

In [3]:
df = pd.read_csv('Sports Data_547601343_1788497867256.csv')
df.head()

,Game_number,Result,Avg_team_Age,Match_light_type,Match_format,Bowlers_in_team,Wicket_keeper_in_team,All_rounder_in_team,First_selection,Opponent,...,Max_run_scored_1over,Max_wicket_taken_1over,Extra_bowls_bowled,Min_run_given_1over,Min_run_scored_1over,Max_run_given_1over,extra_bowls_opponent,player_highest_run,Players_scored_zero,player_highest_wicket
0,Game_1,1,18,Day,ODI,3,1,3,Bowling,Srilanka,...,13,3,0,2,3,6,0,54,3,1
1,Game_2,0,24,Day,T20,3,1,4,Batting,Zimbabwe,...,12,1,0,0,3,6,0,69,2,1
2,Game_3,1,24,Day and Night,T20,3,1,2,Bowling,Zimbabwe,...,14,4,0,0,3,6,0,69,3,1
3,Game_4,0,24,Day,ODI,2,1,2,Bowling,Kenya,...,15,4,0,2,3,6,0,73,3,1
4,Game_5,1,24,Night,ODI,1,1,3,Bowling,Srilanka,...,12,4,0,0,3,6,0,80,3,1

We will check for the missing values.

In [4]:
df.isnull().sum()

Game_number               0
Result                    0
Avg_team_Age              0
Match_light_type          0
Match_format              0
Bowlers_in_team           0
Wicket_keeper_in_team     0
All_rounder_in_team       0
First_selection           0
Opponent                  0
Season                    0
Audience_number           0
Offshore                  0
Max_run_scored_1over      0
Max_wicket_taken_1over    0
Extra_bowls_bowled        0
Min_run_given_1over       0
Min_run_scored_1over      0
Max_run_given_1over       0
extra_bowls_opponent      0
player_highest_run        0
Players_scored_zero       0
player_highest_wicket     0
dtype: int64

There are no missing values in the dataset and we can go ahead with building the model.

We will check the number of rows and the number of columns in the dataframe.

In [5]:
print('The number of rows (observations) is:',df.shape[0],'\n''The number of columns(variables) is:',df.shape[1])

The number of rows (observations) is: 2930
The number of columns(variables) is: 23

We will drop the 'Game_number' variable.

In [6]:
df=df.drop(['Game_number'], axis=1)
df.head()

,Result,Avg_team_Age,Match_light_type,Match_format,Bowlers_in_team,Wicket_keeper_in_team,All_rounder_in_team,First_selection,Opponent,Season,...,Max_run_scored_1over,Max_wicket_taken_1over,Extra_bowls_bowled,Min_run_given_1over,Min_run_scored_1over,Max_run_given_1over,extra_bowls_opponent,player_highest_run,Players_scored_zero,player_highest_wicket
0,1,18,Day,ODI,3,1,3,Bowling,Srilanka,Summer,...,13,3,0,2,3,6,0,54,3,1
1,0,24,Day,T20,3,1,4,Batting,Zimbabwe,Summer,...,12,1,0,0,3,6,0,69,2,1
2,1,24,Day and Night,T20,3,1,2,Bowling,Zimbabwe,Summer,...,14,4,0,0,3,6,0,69,3,1
3,0,24,Day,ODI,2,1,2,Bowling,Kenya,Summer,...,15,4,0,2,3,6,0,73,3,1
4,1,24,Night,ODI,1,1,3,Bowling,Srilanka,Summer,...,12,4,0,0,3,6,0,80,3,1

Let us check the data types of each of the variables in the data.

In [7]:
df.dtypes

Result                    int64
Avg_team_Age              int64
Match_light_type            str
Match_format                str
Bowlers_in_team           int64
Wicket_keeper_in_team     int64
All_rounder_in_team       int64
First_selection             str
Opponent                    str
Season                      str
Audience_number           int64
Offshore                    str
Max_run_scored_1over      int64
Max_wicket_taken_1over    int64
Extra_bowls_bowled        int64
Min_run_given_1over       int64
Min_run_scored_1over      int64
Max_run_given_1over       int64
extra_bowls_opponent      int64
player_highest_run        int64
Players_scored_zero       int64
player_highest_wicket     int64
dtype: object

There are many variables which has the object data type.

sklearn in Python does not take the input of object data types when building Classification Trees. So, we need to convert these variables into some numerical form.

In [8]:
#We are prepping the data by segregating them into Target and independent variables to runt his model going forward

# Let us define the X(predictor) and Y(target) variables

X = df.drop("Result" , axis=1)

Y = df.pop("Result")
#we have made a copy of the data frame as the 'pop' function removes that particular variable from the data frame and stores 
# in another variable

In [9]:
# This line of code is to perform one hot encoding for Categorical Features
X = pd.get_dummies( X, drop_first = False )

In [10]:
list(X.columns)

['Avg_team_Age',
 'Bowlers_in_team',
 'Wicket_keeper_in_team',
 'All_rounder_in_team',
 'Audience_number',
 'Max_run_scored_1over',
 'Max_wicket_taken_1over',
 'Extra_bowls_bowled',
 'Min_run_given_1over',
 'Min_run_scored_1over',
 'Max_run_given_1over',
 'extra_bowls_opponent',
 'player_highest_run',
 'Players_scored_zero',
 'player_highest_wicket',
 'Match_light_type_Day',
 'Match_light_type_Day and Night',
 'Match_light_type_Night',
 'Match_format_20-20',
 'Match_format_ODI',
 'Match_format_T20',
 'Match_format_Test',
 'First_selection_Batting',
 'First_selection_Bowling',
 'Opponent_Australia',
 'Opponent_Bangladesh',
 'Opponent_England',
 'Opponent_Kenya',
 'Opponent_Pakistan',
 'Opponent_South Africa',
 'Opponent_Srilanka',
 'Opponent_West Indies',
 'Opponent_Zimbabwe',
 'Season_Rainy',
 'Season_Summer',
 'Season_Winter',
 'Offshore_No',
 'Offshore_Yes']

In [11]:
X.dtypes

Avg_team_Age                      int64
Bowlers_in_team                   int64
Wicket_keeper_in_team             int64
All_rounder_in_team               int64
Audience_number                   int64
Max_run_scored_1over              int64
Max_wicket_taken_1over            int64
Extra_bowls_bowled                int64
Min_run_given_1over               int64
Min_run_scored_1over              int64
Max_run_given_1over               int64
extra_bowls_opponent              int64
player_highest_run                int64
Players_scored_zero               int64
player_highest_wicket             int64
Match_light_type_Day               bool
Match_light_type_Day and Night     bool
Match_light_type_Night             bool
Match_format_20-20                 bool
Match_format_ODI                   bool
Match_format_T20                   bool
Match_format_Test                  bool
First_selection_Batting            bool
First_selection_Bowling            bool
Opponent_Australia                 bool
Opponent_Bangladesh                bool
Opponent_England                   bool
Opponent_Kenya                     bool
Opponent_Pakistan                  bool
Opponent_South Africa              bool
Opponent_Srilanka                  bool
Opponent_West Indies               bool
Opponent_Zimbabwe                  bool
Season_Rainy                       bool
Season_Summer                      bool
Season_Winter                      bool
Offshore_No                        bool
Offshore_Yes                       bool
dtype: object

#We see that the data types of all the variables have been changed to either of integer64 or boolean.

In [12]:
X.head()

,Avg_team_Age,Bowlers_in_team,Wicket_keeper_in_team,All_rounder_in_team,Audience_number,Max_run_scored_1over,Max_wicket_taken_1over,Extra_bowls_bowled,Min_run_given_1over,Min_run_scored_1over,...,Opponent_Pakistan,Opponent_South Africa,Opponent_Srilanka,Opponent_West Indies,Opponent_Zimbabwe,Season_Rainy,Season_Summer,Season_Winter,Offshore_No,Offshore_Yes
0,18,3,1,3,9940,13,3,0,2,3,...,False,False,True,False,False,False,True,False,True,False
1,24,3,1,4,8400,12,1,0,0,3,...,False,False,False,False,True,False,True,False,True,False
2,24,3,1,2,13146,14,4,0,0,3,...,False,False,False,False,True,False,True,False,False,True
3,24,2,1,2,7357,15,4,0,2,3,...,False,False,False,False,False,False,True,False,True,False
4,24,1,1,3,13328,12,4,0,0,3,...,False,False,True,False,False,False,True,False,True,False

## Split the data into Train and Test.

Before building the model we should split the data into Train and Test. We will thus build a model on the training data and use this model to predict on the test data.

Before splitting the data, we shall make a copy of the data frame.

In [13]:
data = df.copy()
data.head()
#Just keeping the copy of the original dataset.

,Avg_team_Age,Match_light_type,Match_format,Bowlers_in_team,Wicket_keeper_in_team,All_rounder_in_team,First_selection,Opponent,Season,Audience_number,...,Max_run_scored_1over,Max_wicket_taken_1over,Extra_bowls_bowled,Min_run_given_1over,Min_run_scored_1over,Max_run_given_1over,extra_bowls_opponent,player_highest_run,Players_scored_zero,player_highest_wicket
0,18,Day,ODI,3,1,3,Bowling,Srilanka,Summer,9940,...,13,3,0,2,3,6,0,54,3,1
1,24,Day,T20,3,1,4,Batting,Zimbabwe,Summer,8400,...,12,1,0,0,3,6,0,69,2,1
2,24,Day and Night,T20,3,1,2,Bowling,Zimbabwe,Summer,13146,...,14,4,0,0,3,6,0,69,3,1
3,24,Day,ODI,2,1,2,Bowling,Kenya,Summer,7357,...,15,4,0,2,3,6,0,73,3,1
4,24,Night,ODI,1,1,3,Bowling,Srilanka,Summer,13328,...,12,4,0,0,3,6,0,80,3,1

In [14]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=.30, random_state=1)

Now that we have split the data into Train and Test, let us go ahead and build our Decision Tree Model.

## Building the Decision Tree

We will start by building a very basic Decision Tree model.

In [15]:
from sklearn import tree

In [16]:
dt_model = tree.DecisionTreeClassifier(criterion = 'gini',random_state=1,min_samples_split=2,
    min_samples_leaf=1)

After defining the decision tree, we will build the model on the training data.

In [17]:
dt_model.fit(X_train, Y_train)

DecisionTreeClassifier(random_state=1)

We will check the importance of the variables in the Classification Tree that we just built.

In [18]:
pd.Series(dt_model.feature_importances_,index=X_train.columns).sort_values(ascending=False)

Audience_number                   0.179453
player_highest_run                0.147419
Extra_bowls_bowled                0.064608
Players_scored_zero               0.057469
Offshore_No                       0.054086
extra_bowls_opponent              0.052714
All_rounder_in_team               0.048938
Season_Summer                     0.046588
Min_run_scored_1over              0.044403
Max_run_scored_1over              0.043655
Opponent_South Africa             0.037016
Bowlers_in_team                   0.036900
Max_run_given_1over               0.026936
Max_wicket_taken_1over            0.023362
Opponent_Kenya                    0.021576
player_highest_wicket             0.014722
Min_run_given_1over               0.012398
Opponent_Srilanka                 0.011646
Match_light_type_Day and Night    0.009251
Opponent_Pakistan                 0.008228
Avg_team_Age                      0.008143
Opponent_Australia                0.007570
Season_Winter                     0.007542
Match_format_T20                  0.007477
Match_format_ODI                  0.006206
Match_light_type_Night            0.004860
Opponent_England                  0.004638
First_selection_Bowling           0.004073
Opponent_Zimbabwe                 0.002662
First_selection_Batting           0.002413
Opponent_Bangladesh               0.001600
Season_Rainy                      0.001450
Wicket_keeper_in_team             0.000000
Match_light_type_Day              0.000000
Match_format_Test                 0.000000
Match_format_20-20                0.000000
Opponent_West Indies              0.000000
Offshore_Yes                      0.000000
dtype: float64

From the above output, we can see that 'Audience_number' is the most important variable followed by 'player_highest_run' and so on.

We will now find the overall accuracy of the train and test data using the model that we just built.

In [19]:
#Train Data
dt_model.score(X_train,Y_train)

1.0

In [20]:
#Test Data
dt_model.score(X_test,Y_test)

0.9101251422070534

The accuracy on the Training Data is 100% and the accuracy on the Test Data is lesser - 91%. The model has surely been overfitted. 
Thus, we need to prune or regularize the tree.

## Pruning/Regularizing the Tree

For Pruning/Regularizing the Tree we need to be sure as to what parameters and how to prune the tree.

# Method 1 for Pruning:

In [21]:
reg_dt_model = tree.DecisionTreeClassifier(criterion = 'gini', 
                                       max_depth=13,#upto this depth is where the tree has grown uniformly
                                      min_samples_leaf=30, #ensures that every terminal node (leaf node) have at least 10
                                      #observations in it
                                      min_samples_split=10) #for every node to be split into two child nodes that particular
                                      #node should have at least 30 observations

In [22]:
reg_dt_model.fit(X_train, Y_train)

DecisionTreeClassifier(max_depth=13, min_samples_leaf=30, min_samples_split=10)

In [23]:
pd.Series(reg_dt_model.feature_importances_,index=X_train.columns).sort_values(ascending=False)

Audience_number                   0.258917
Offshore_Yes                      0.171362
Season_Summer                     0.105205
Opponent_South Africa             0.099957
Extra_bowls_bowled                0.073443
extra_bowls_opponent              0.071057
player_highest_run                0.063008
All_rounder_in_team               0.058730
Min_run_scored_1over              0.017105
player_highest_wicket             0.017101
Match_light_type_Day and Night    0.012693
Max_wicket_taken_1over            0.010843
Season_Rainy                      0.009736
Match_format_ODI                  0.008748
First_selection_Bowling           0.006776
Avg_team_Age                      0.004698
First_selection_Batting           0.003990
Min_run_given_1over               0.003961
Opponent_Kenya                    0.002670
Max_run_scored_1over              0.000000
Bowlers_in_team                   0.000000
Wicket_keeper_in_team             0.000000
Match_format_Test                 0.000000
Match_format_T20                  0.000000
Match_format_20-20                0.000000
Match_light_type_Night            0.000000
Match_light_type_Day              0.000000
Players_scored_zero               0.000000
Max_run_given_1over               0.000000
Opponent_Bangladesh               0.000000
Opponent_Pakistan                 0.000000
Opponent_England                  0.000000
Opponent_Australia                0.000000
Opponent_Srilanka                 0.000000
Opponent_Zimbabwe                 0.000000
Opponent_West Indies              0.000000
Season_Winter                     0.000000
Offshore_No                       0.000000
dtype: float64

We will now predict both the classes and the probability values on the test data using the Pruned/Regularized Decision Tree.

In [24]:
Y_train_predict_class = reg_dt_model.predict(X_train)
Y_test_predict_class = reg_dt_model.predict(X_test)

In [25]:
Y_train_predict_prob = reg_dt_model.predict_proba(X_train)
Y_test_predict_prob = reg_dt_model.predict_proba(X_test)

# Evaluation of the Train and Test Models.

We will mow build the confusion matrix.

In [26]:
from sklearn import metrics

First we will evaluate the model on the Training Data.

In [27]:
print(metrics.confusion_matrix(Y_train,Y_train_predict_class))

[[1651   71]
 [ 192  137]]

In [28]:
tn, fp, fn, tp = metrics.confusion_matrix(Y_train,Y_train_predict_class).ravel()
print('True Negative:',tn,'\n''False Positives:' ,fp,'\n''False Negatives:', fn,'\n''True Positives:', tp)

True Negative: 1651
False Positives: 71
False Negatives: 192
True Positives: 137

Let us now go ahead and print the classification report to check the various other parameters.

In [29]:
print(metrics.classification_report(Y_train,Y_train_predict_class))

              precision    recall  f1-score   support

           0       0.90      0.96      0.93      1722
           1       0.66      0.42      0.51       329

    accuracy                           0.87      2051
   macro avg       0.78      0.69      0.72      2051
weighted avg       0.86      0.87      0.86      2051

We have been able to predict 87% of the target variables correctly.

We will now check the confusion matrix for the test data.

In [30]:
print(metrics.confusion_matrix(Y_test,Y_test_predict_class),'\n')
tn, fp, fn, tp = metrics.confusion_matrix(Y_test,Y_test_predict_class).ravel()
print('True Negative:',tn,'\n''False Positives:' ,fp,'\n''False Negatives:', fn,'\n''True Positives:', tp)

[[688  47]
 [ 98  46]]

True Negative: 688
False Positives: 47
False Negatives: 98
True Positives: 46

Let us now go ahead and print the classification report for the test data and compare between train and test.

In [31]:
print(metrics.classification_report(Y_test,Y_test_predict_class))

              precision    recall  f1-score   support

           0       0.88      0.94      0.90       735
           1       0.49      0.32      0.39       144

    accuracy                           0.84       879
   macro avg       0.68      0.63      0.65       879
weighted avg       0.81      0.84      0.82       879

In [32]:
#We have been able to predict 84% of the target variables correctly.

# END